name: Actionlint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:       
    - uses: actions/checkout@v3
    
    - name: ActionLint
      uses: devops-actions/actionlint@v0.1.1
      continue-on-error: true
      id: action-lint
    
    - name: Publish results
      uses: actions/upload-artifact@v3
      with:
        name: actionlint-results
        path: ${{ steps.action-lint.outputs.results-file }}
